module.exports = {
	FRONT_FETCH_LIST: 0,
	FRONT_FETCH_DETAIL: 1,
	COLLECTION_FETCH_LIST: 2,
	COLLECTION_FETCH_DETAIL: 3,
	EXHIBITION_FETCH_LIST: 4,
	NODE_FETCH: 5,
	ACTIVITY_FETCH_LIST: 6,
	ACTIVITY_FETCH_DETAIL: 7,

	PUBLIC_IMG_BASE: 'http://moca-yinchuan.com/admin/sites/default/files/'
};
